<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\MarkedAs;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $cats   = Category::pluck('id', 'slug');
        $brands = Brand::pluck('id', 'name');
        $marks  = MarkedAs::pluck('id', 'name');

        // Determine run number so each execution produces unique SKUs
        $run = intdiv(Product::withTrashed()->count(), 10) + 1;
        $suffix = $run === 1 ? '' : "-R{$run}";

        $products = [
            // ── Gaming Laptops ────────────────────────────────────────────────
            [
                'category_id'     => $cats['gaming-laptops'],
                'brand_id'        => $brands['ASUS'],
                'marked_as_id'    => $marks['Featured'],
                'name'            => 'ASUS ROG Strix G16',
                'sku'             => 'GL-001',
                'series'          => 'ROG Strix',
                'processor'       => 'Intel Core i9-14900HX',
                'processor_type'  => 'Intel Core i9',
                'generation'      => '14th Gen',
                'ram'             => '16GB',
                'ram_type'        => 'DDR5',
                'storage'         => '1TB NVMe SSD',
                'graphical_memory'=> '8GB GDDR6 (RTX 4070)',
                'screen_size'     => '16"',
                'color'           => 'Eclipse Black',
                'backlight'       => true,
                'price'           => 1499.99,
                'discount_percent'=> 5,
                'stock_quantity'  => 35,
                'warranty_months' => 24,
                'is_active'       => true,
                'status'          => true,
                'description'     => 'Dominate every game with the ASUS ROG Strix G16. Powered by the Intel Core i9-14900HX and NVIDIA GeForce RTX 4070, it features a 16" 240Hz QHD display, 16GB DDR5 RAM, and a 1TB NVMe SSD. Built for serious gamers who demand peak performance.',
            ],
            [
                'category_id'     => $cats['gaming-laptops'],
                'brand_id'        => $brands['Acer'],
                'marked_as_id'    => $marks['Best Seller'],
                'name'            => 'Acer Predator Helios 16',
                'sku'             => 'GL-002',
                'series'          => 'Predator Helios',
                'processor'       => 'Intel Core i7-14700HX',
                'processor_type'  => 'Intel Core i7',
                'generation'      => '14th Gen',
                'ram'             => '16GB',
                'ram_type'        => 'DDR5',
                'storage'         => '1TB NVMe SSD',
                'graphical_memory'=> '8GB GDDR6 (RTX 4060)',
                'screen_size'     => '16"',
                'color'           => 'Abyssal Black',
                'backlight'       => true,
                'price'           => 1299.99,
                'discount_percent'=> 3,
                'stock_quantity'  => 42,
                'warranty_months' => 24,
                'is_active'       => true,
                'status'          => true,
                'description'     => 'The Acer Predator Helios 16 delivers exceptional gaming performance with its Intel Core i7-14700HX and RTX 4060. Enjoy a stunning QHD 165Hz display and a 1TB SSD for fast load times. A top pick for mid-range gaming power.',
            ],

            // ── Business Laptops ──────────────────────────────────────────────
            [
                'category_id'     => $cats['business-laptops'],
                'brand_id'        => $brands['Dell'],
                'marked_as_id'    => $marks['Sale'],
                'name'            => 'Dell Latitude 5540',
                'sku'             => 'BL-001',
                'series'          => 'Latitude 5000',
                'processor'       => 'Intel Core i7-1355U',
                'processor_type'  => 'Intel Core i7',
                'generation'      => '13th Gen',
                'ram'             => '16GB',
                'ram_type'        => 'DDR4',
                'storage'         => '512GB NVMe SSD',
                'graphical_memory'=> 'Integrated Intel Iris Xe',
                'screen_size'     => '15.6"',
                'color'           => 'Titan Grey',
                'backlight'       => true,
                'price'           => 899.99,
                'discount_percent'=> 10,
                'stock_quantity'  => 80,
                'warranty_months' => 36,
                'is_active'       => true,
                'status'          => true,
                'description'     => 'The Dell Latitude 5540 is engineered for business professionals who need reliability. Featuring a 13th Gen Intel Core i7, 16GB DDR4 RAM, 512GB SSD, and a crisp 15.6" FHD display with fingerprint reader and TPM 2.0 security.',
            ],
            [
                'category_id'     => $cats['business-laptops'],
                'brand_id'        => $brands['HP'],
                'marked_as_id'    => $marks['Top Rated'],
                'name'            => 'HP EliteBook 840 G10',
                'sku'             => 'BL-002',
                'series'          => 'EliteBook 800',
                'processor'       => 'Intel Core i7-1365U',
                'processor_type'  => 'Intel Core i7',
                'generation'      => '13th Gen',
                'ram'             => '32GB',
                'ram_type'        => 'LPDDR5',
                'storage'         => '1TB NVMe SSD',
                'graphical_memory'=> 'Integrated Intel Iris Xe',
                'screen_size'     => '14"',
                'color'           => 'Silver',
                'backlight'       => true,
                'price'           => 1049.99,
                'discount_percent'=> 8,
                'stock_quantity'  => 55,
                'warranty_months' => 36,
                'is_active'       => true,
                'status'          => true,
                'description'     => 'The HP EliteBook 840 G10 is the ultimate business companion. Built with enterprise-grade security, 32GB LPDDR5 RAM, a 1TB SSD, and a sleek 14" FHD display. Includes HP Wolf Security and AI-powered audio for professional meetings.',
            ],

            // ── Ultrabooks ────────────────────────────────────────────────────
            [
                'category_id'     => $cats['ultrabooks'],
                'brand_id'        => $brands['Apple'],
                'marked_as_id'    => $marks['Top Deal'],
                'name'            => 'Apple MacBook Air 15" M4',
                'sku'             => 'UL-001',
                'series'          => 'MacBook Air',
                'processor'       => 'Apple M4',
                'processor_type'  => 'Apple Silicon',
                'generation'      => 'M4',
                'ram'             => '16GB',
                'ram_type'        => 'Unified Memory',
                'storage'         => '512GB SSD',
                'graphical_memory'=> '10-core GPU (Integrated)',
                'screen_size'     => '15.3"',
                'color'           => 'Midnight',
                'backlight'       => true,
                'price'           => 1299.99,
                'discount_percent'=> 0,
                'stock_quantity'  => 60,
                'warranty_months' => 12,
                'is_active'       => true,
                'status'          => true,
                'description'     => 'The MacBook Air with M4 chip delivers extraordinary performance in a fanless, ultra-thin design. Enjoy an all-day 18-hour battery, a stunning 15.3" Liquid Retina display, and 16GB of unified memory — all in a 1.51kg chassis.',
            ],
            [
                'category_id'     => $cats['ultrabooks'],
                'brand_id'        => $brands['Lenovo'],
                'marked_as_id'    => $marks['Normal'],
                'name'            => 'Lenovo Yoga Slim 7i',
                'sku'             => 'UL-002',
                'series'          => 'Yoga Slim 7',
                'processor'       => 'Intel Core Ultra 7 155U',
                'processor_type'  => 'Intel Core Ultra 7',
                'generation'      => 'Meteor Lake',
                'ram'             => '16GB',
                'ram_type'        => 'LPDDR5X',
                'storage'         => '1TB NVMe SSD',
                'graphical_memory'=> 'Integrated Intel Arc Graphics',
                'screen_size'     => '14"',
                'color'           => 'Platinum Grey',
                'backlight'       => true,
                'price'           => 949.99,
                'discount_percent'=> 7,
                'stock_quantity'  => 45,
                'warranty_months' => 24,
                'is_active'       => true,
                'status'          => true,
                'description'     => 'The Lenovo Yoga Slim 7i combines elegance with power. At just 1.2kg, it packs an Intel Core Ultra 7 processor, 16GB LPDDR5X RAM, a gorgeous 14" 2.8K OLED display, and a 1TB SSD — ideal for professionals on the go.',
            ],

            // ── Workstation Laptops ───────────────────────────────────────────
            [
                'category_id'     => $cats['workstation-laptops'],
                'brand_id'        => $brands['Dell'],
                'marked_as_id'    => $marks['Featured'],
                'name'            => 'Dell Precision 5690',
                'sku'             => 'WL-001',
                'series'          => 'Precision 5000',
                'processor'       => 'Intel Core Ultra 9 185H',
                'processor_type'  => 'Intel Core Ultra 9',
                'generation'      => 'Meteor Lake',
                'ram'             => '64GB',
                'ram_type'        => 'DDR5',
                'storage'         => '2TB NVMe SSD',
                'graphical_memory'=> '12GB GDDR6 (RTX 3000 Ada)',
                'screen_size'     => '16"',
                'color'           => 'Platinum Silver',
                'backlight'       => true,
                'price'           => 2199.99,
                'discount_percent'=> 5,
                'stock_quantity'  => 15,
                'warranty_months' => 36,
                'is_active'       => true,
                'status'          => true,
                'description'     => 'The Dell Precision 5690 is a powerhouse workstation for engineers, architects, and content creators. Featuring 64GB DDR5 RAM, an NVIDIA RTX 3000 Ada workstation GPU, 2TB SSD, and a 16" 4K touch display with Calman-verified colour accuracy.',
            ],
            [
                'category_id'     => $cats['workstation-laptops'],
                'brand_id'        => $brands['Lenovo'],
                'marked_as_id'    => $marks['Best Seller'],
                'name'            => 'Lenovo ThinkPad P16s Gen 3',
                'sku'             => 'WL-002',
                'series'          => 'ThinkPad P',
                'processor'       => 'AMD Ryzen 9 PRO 7940HS',
                'processor_type'  => 'AMD Ryzen 9',
                'generation'      => 'Ryzen 7000',
                'ram'             => '32GB',
                'ram_type'        => 'DDR5',
                'storage'         => '1TB NVMe SSD',
                'graphical_memory'=> '4GB GDDR6 (NVIDIA RTX A500)',
                'screen_size'     => '16"',
                'color'           => 'Thunder Black',
                'backlight'       => true,
                'price'           => 1799.99,
                'discount_percent'=> 4,
                'stock_quantity'  => 20,
                'warranty_months' => 36,
                'is_active'       => true,
                'status'          => true,
                'description'     => 'Built for demanding professional workloads, the ThinkPad P16s Gen 3 pairs an AMD Ryzen 9 PRO with an NVIDIA RTX A500 GPU. ISV-certified, with 32GB DDR5 RAM, 1TB SSD, and a 16" WUXGA IPS anti-glare display.',
            ],

            // ── 2-in-1 Laptops ────────────────────────────────────────────────
            [
                'category_id'     => $cats['2-in-1-laptops'],
                'brand_id'        => $brands['Microsoft'],
                'marked_as_id'    => $marks['Top Rated'],
                'name'            => 'Microsoft Surface Laptop 6',
                'sku'             => '2I-001',
                'series'          => 'Surface Laptop',
                'processor'       => 'Intel Core Ultra 7 165H',
                'processor_type'  => 'Intel Core Ultra 7',
                'generation'      => 'Meteor Lake',
                'ram'             => '16GB',
                'ram_type'        => 'LPDDR5x',
                'storage'         => '1TB SSD',
                'graphical_memory'=> 'Integrated Intel Arc Graphics',
                'screen_size'     => '13.5"',
                'color'           => 'Sapphire',
                'backlight'       => true,
                'price'           => 1099.99,
                'discount_percent'=> 6,
                'stock_quantity'  => 38,
                'warranty_months' => 12,
                'is_active'       => true,
                'status'          => true,
                'description'     => 'The Microsoft Surface Laptop 6 features a stunning 13.5" PixelSense touchscreen, Intel Core Ultra 7, 16GB LPDDR5x RAM, and 1TB SSD. Supports Surface Slim Pen 2 and offers near-instant wake with Windows Hello facial recognition.',
            ],
            [
                'category_id'     => $cats['2-in-1-laptops'],
                'brand_id'        => $brands['HP'],
                'marked_as_id'    => $marks['Sale'],
                'name'            => 'HP Envy x360 16',
                'sku'             => '2I-002',
                'series'          => 'Envy x360',
                'processor'       => 'AMD Ryzen 7 8840HS',
                'processor_type'  => 'AMD Ryzen 7',
                'generation'      => 'Ryzen 8000',
                'ram'             => '16GB',
                'ram_type'        => 'LPDDR5',
                'storage'         => '1TB NVMe SSD',
                'graphical_memory'=> 'Integrated AMD Radeon 780M',
                'screen_size'     => '16"',
                'color'           => 'Meteor Silver',
                'backlight'       => true,
                'price'           => 849.99,
                'discount_percent'=> 9,
                'stock_quantity'  => 50,
                'warranty_months' => 12,
                'is_active'       => true,
                'status'          => true,
                'description'     => 'The HP Envy x360 16 is a versatile 2-in-1 with a 360-degree hinge, AMD Ryzen 7 8840HS, 16GB LPDDR5, and 1TB NVMe SSD. The 16" FHD+ OLED touch display with HP MPP 2.0 stylus support makes it ideal for creative professionals.',
            ],
        ];

        foreach ($products as $data) {
            $data['sku']  = $data['sku'] . $suffix;
            $data['name'] = $run === 1 ? $data['name'] : $data['name'] . " (v{$run})";
            $data['slug'] = Str::slug($data['name']);
            Product::updateOrCreate(['sku' => $data['sku']], $data);
        }
    }
}
